CREATE TABLE IF NOT EXISTS budget_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    subtotal NUMERIC DEFAULT 0,
    paid NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE budget_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON budget_items
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON budget_items
    FOR ALL USING (auth.role() = 'authenticated');
