
-- Create budget_items table
CREATE TABLE IF NOT EXISTS budget_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    amount numeric NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- Create budget_payments table
CREATE TABLE IF NOT EXISTS budget_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text,
    description text NOT NULL,
    amount numeric NOT NULL DEFAULT 0,
    status text,
    created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE budget_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_payments ENABLE ROW LEVEL SECURITY;

-- Create Policies (Admin Only)
CREATE POLICY "Enable read for admins" ON budget_items
    FOR SELECT
    USING (auth.role() = 'authenticated'); -- Logic handled by app + auth context checking specific emails if needed, but 'authenticated' is a good baseline + role check

CREATE POLICY "Enable all for admins" ON budget_items
    FOR ALL
    USING (auth.role() = 'authenticated');

CREATE POLICY "Enable read for admins" ON budget_payments
    FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Enable all for admins" ON budget_payments
    FOR ALL
    USING (auth.role() = 'authenticated');

-- Seed Data
INSERT INTO budget_items (category, amount) VALUES
('Alquiler', 0.0),
('Menu', 26242.0),
('Barra Libre', 1500.0),
('DJ/Audio', 1250.0),
('Ceremonia', 0.0),
('Alquiler bus', 1500.0),
('Hotel Adrian Oficiante boda', 320.0),
('Hotel Alessia', 280.0),
('Fotografo y videografo', 2350.0),
('Fotomatón', 314.0),
('Jamón y cortadores', 900.0),
('Bomboniere', 955.0),
('Alpargatas para chicas', 260.0),
('Cosas de temu', 150.0),
('Paint and Wine', 350.0),
('Voli', 667.0),
('Apartamento famiglia Zingali', 450.0),
('Preboda', 2760.0),
('Banchitu in Sicilia', 3259.0),
('Alianze', 1200.0),
('Wedding Planner', 0.0);
